#!/bin/bash

# Migration Helper Script
# This script helps you apply the SEO enrichments migration to Supabase

echo "🗄️  Supabase Migration Helper"
echo "================================"
echo ""
echo "This script will help you apply the recipe_seo_enrichments table migration."
echo ""
echo "📋 Migration File:"
echo "   supabase/migrations/20250118_get_unenriched_recipes.sql"
echo ""
echo "🔧 Steps to Apply Migration:"
echo ""
echo "1. Open your Supabase dashboard:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. Select your project"
echo ""
echo "3. Go to 'SQL Editor' in the left sidebar"
echo ""
echo "4. Click 'New Query'"
echo ""
echo "5. Copy and paste the SQL from:"
echo "   supabase/migrations/20250118_get_unenriched_recipes.sql"
echo ""
echo "6. Click 'Run' to execute the migration"
echo ""
echo "✅ After migration, you can test enrichment with:"
echo "   npm run enrich:seo -- --recipe-id 52772"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 Migration SQL Preview:"
echo ""
cat supabase/migrations/20250118_get_unenriched_recipes.sql
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
